---
nomad_version: "0.12.5"
nomad_checksum: "sha256:bb133b8dd0442fe59a884a0db19373d0680f27af00d5b1ae73d4487a586327db"
nomad_install_path: /usr/local/nomad
nomad_dc: alpha
nomad_is_server: no
nomad_leader_group: nomad_servers
nomad_bootstrap_expect: "{{ groups[nomad_leader_group] | length }}"
nomad_retry_join: ' [{% for host in groups[nomad_leader_group] %}"{{ host }}"{% if not loop.last %}, {% endif %}{% endfor %}]'
