---
nomad_version: "1.0.1"
nomad_checksum: "sha256:b0ce81f47bccfbb74095f75d0b2410fcfaafb0cd4d79429bab4ef35f1b7be004"
nomad_install_path: /usr/local/nomad
nomad_dc: alpha
nomad_is_server: no
nomad_leader_group: nomad_servers
nomad_bootstrap_expect: "{{ groups[nomad_leader_group] | length }}"
nomad_retry_join: ' [{% for host in groups[nomad_leader_group] %}"{{ host }}"{% if not loop.last %}, {% endif %}{% endfor %}]'
