#!/usr/bin/env ansible-playbook -i inventory --skip-tags=consul,bootstrap,nomad
---
- name: setup servers
  hosts: hosts
  gather_facts: true
  remote_user: pi
  become: yes
  become_user: root
  roles:
    - { role: utils, tags: ["utils"] }
  tags:
    - bootstrap
