---
traefik_version: "v2.2.11"
traefik_systemd_unit_template: traefik.service.j2
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_install_dir: /usr/bin
traefik_bin_path: "{{ traefik_install_dir }}/traefik"
traefik_config_directory: /etc/traefik.d
traefik_binary_url: https://github.com/containous/traefik/releases/download/{{traefik_version}}/traefik_{{traefik_version}}_linux_armv7.tar.gz
traefik_checksum: "sha256:9c79c181b668dcaa0e634516b6da68738075c812261b301c385a251b389e1447"
traefik_config_template: traefik.toml.j2
traefik_config_file: /etc/traefik.toml
traefix_dashboard_template: dashboard.toml.j2
traefik_dashboard_file: "{{ traefik_config_directory }}/dashboard.toml"
traefik_update: yes
traefix_dashboard_items:
  - name: docker
    host: docker.veverka.net
    service: dockerregistry@consulcatalog
    include_auth: false
  - name: freshrss
    host: freshrss.veverka.net
    service: freshrss@consulcatalog
    include_auth: false
  - name: influxdb
    host: influxdb.veverka.net
    service: influxdb@consulcatalog
    include_auth: false
  - name: jackett
    host: jackett.veverka.net
    service: jackett@consulcatalog
    include_auth: false
  - name: lazylibrarian
    host: lazylibrarian.veverka.net
    service: lazylibrarian@consulcatalog
    include_auth: false
  - name: library
    host: library.veverka.net
    service: calibreweb@consulcatalog
    include_auth: false
  - name: minio
    host: minio.veverka.net
    service: minio@consulcatalog
    include_auth: false
  - name: minioext
    host: minioext.veverka.net
    service: minio@consulcatalog
    include_auth: false
  - name: nomad
    host: nomad.veverka.net
    service: nomad-client@consulcatalog
    include_auth: true
  - name: ombi
    host: ombi.veverka.net
    service: ombi@consulcatalog
    include_auth: false
  - name: radarr
    host: radarr.veverka.net
    service: radarr@consulcatalog
    include_auth: false
  - name: registry
    host: registry.veverka.net
    service: dockerregistry@consulcatalog
    include_auth: true
  - name: sonarr
    host: sonarr.veverka.net
    service: sonarr@consulcatalog
    include_auth: false
  - name: tautulli
    host: tautulli.veverka.net
    service: tautulli@consulcatalog
    include_auth: false
