---
traefik_version: "v2.4.0"
traefik_systemd_unit_template: traefik.service.j2
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_install_dir: /usr/bin
traefik_bin_path: "{{ traefik_install_dir }}/traefik"
traefik_config_directory: /etc/traefik.d
traefik_binary_url: https://github.com/containous/traefik/releases/download/{{traefik_version}}/traefik_{{traefik_version}}_linux_armv7.tar.gz
traefik_checksum: "sha256:83ca871c22443dd3b76c6a8ad2e5611bf2bb0ae7beba47d3cfaa94f1d99f59fe"
traefik_config_template: traefik.toml.j2
traefik_config_file: /etc/traefik.toml
traefix_dashboard_template: dashboard.toml.j2
traefik_dashboard_file: "{{ traefik_config_directory }}/dashboard.toml"
traefik_update: no
traefix_static_items:
  - name: bazarr
    url: http://192.168.1.111:6767
  - name: library
    url: http://192.168.1.111:8083
  - name: movie_api
    url: http://192.168.1.111:8013
  - name: ombi
    url: http://192.168.1.111:3579
  - name: radarr
    url: http://192.168.1.111:7878
  - name: requests
    url: http://192.168.1.111:3579
  - name: sonarr
    url: http://192.168.1.111:8989
  - name: tautulli
    url: http://192.168.1.111:8181
  - name: gitlab
    url: http://192.168.1.104
  - name: glce
    url: http://192.168.1.104
traefix_dashboard_items:
  - name: docker
    host: docker.veverka.net
    service: dockerregistry@consulcatalog
    include_auth: false
  - name: jackett
    host: jackett.veverka.net
    service: jackett@consulcatalog
    include_auth: false
  - name: nomad
    host: nomad.veverka.net
    service: nomad-client@consulcatalog
    include_auth: true
  - name: registry
    host: registry.veverka.net
    service: dockerregistry@consulcatalog
    include_auth: true
