- name: Create folders
  file:
    path: "{{ item.name }}"
    state: directory
  loop:
    - { name: "/mnt/rpi1-movies", source: "//192.168.1.231/external/Movies" }
    - { name: "/mnt/rpi1-tv", source: "//192.168.1.231/external/TV" }

    - { name: "/mnt/qnap-tv", source: "//192.168.1.43/VIDEO/TV" }
    - { name: "/mnt/configs", source: "//192.168.1.43/Public/NomadConfigs" }
  tags:
    - dockermnt

- name: Mount directories for radarr (using pi)
  mount:
    name: "{{ item.name }}"
    src:  "{{ item.source }}"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
  loop:
    - { name: "/mnt/rpi1-movies", source: "//192.168.1.231/external/Movies" }
    - { name: "/mnt/configs", source: "//192.168.1.43/Public/NomadConfigs" }
  tags:
    - dockermnt

- name: Mount directories for sonarr
  mount:
    name: "{{ item.name }}"
    src:  "{{ item.source }}"
    opts: "noacl,uid=sonarr,gid=sonarr,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
  loop:
    - { name: "/mnt/rpi1-tv", source: "//192.168.1.231/external/TV" }
    - { name: "/mnt/qnap-tv", source: "//192.168.1.43/VIDEO/TV" }
  tags:
    - dockermnt
