---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600
- name: Install packages
  apt:
    pkg:
      - curl
      - dnsutils
      - cifs-utils
      - git
      - htop
      - net-tools
      - telnet
      - unzip
      - wget
      - zsh
  tags:
    - apt
