# tasks file for kibatic.traefik
---
- name: Create Traefik systemd unit
  template:
    src: "{{ traefik_systemd_unit_template }}"
    dest: "{{ traefik_systemd_unit_dest }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart traefik
  when: traefik_update | bool == True

- name: create systemd override directory
  file:
    path: /etc/systemd/system/traefik.service.d
    state: directory
  when: traefik_update | bool == True

- name: add systemd override
  copy:
    src: override.conf
    dest: /etc/systemd/system/traefik.service.d/override.conf
  when: traefik_update | bool == True

- name: Ensure Traefik install directory exists
  file:
    path: "{{ traefik_install_dir }}"
    state: directory

- name: Ensure Traefik config directory exists
  file:
    path: "{{ traefik_config_directory }}"
    state: directory

- name: Download Traefik binary
  get_url:
    url: "{{ traefik_binary_url }}"
    dest: /tmp/traefik.tar.gz
    mode: 0777
    checksum: "{{ traefik_checksum }}"
    force: true
  when: traefik_update | bool == True

- name: Ensure Traefik service is stopped before Traefik update
  service:
    name: traefik
    state: stopped
    enabled: yes

- name: Decompress Traefik archive
  unarchive:
    src: /tmp/traefik.tar.gz
    dest: "{{ traefik_install_dir }}"
    remote_src: yes
  when: traefik_update | bool == True

- name: Copy Traefik config file
  template:
    src: "{{ traefik_config_template }}"
    dest: "{{ traefik_config_file }}"
    owner: root
    group: root
    backup: true
    mode: 0744
  notify:
    - Restart traefik

- name: Copy Traefik dashboard config file
  template:
    src: "{{ traefix_dashboard_template }}"
    dest: "{{ traefik_dashboard_file }}"
    owner: root
    group: root
    backup: true
    mode: 0744
  notify:
    - Restart traefik

- name: Copy Traefik redirect file
  copy:
    src: redirect.toml
    dest: "{{ traefik_config_directory }}/redirect.toml"
    owner: root
    group: root
    backup: true
    mode: 0744
  notify:
    - Restart traefik

- name: Ensure traefik service is enabled and running
  systemd:
    name: traefik
    state: started
    enabled: yes
    daemon_reload: yes
